application:
  name: shipment
  scheduler:
      shipment-dispatcher:
        enabled: true
        cron: "0 0/1 * 1/1 * ?"
server:
  port: 8082
  servlet:
    context-path: /store
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
#logging:
#  level:
#    org:
#      springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/store_consumer
    name: store_consumer
    username: store
    password: store
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      #      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    admin:
      properties:
        bootstrap.servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: consumer-1
      properties:
        spring.json.trusted.packages: "com.jordanec.store.*"
        acks: all
        retries: 3
        retry.backoff.ms: 1000
logging:
  level:
    root: INFO
    com:
      jordanec: DEBUG
#    org:
#      springframework: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/store_consumer
    name: store_consumer
    username: root
    password: 54321
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      #      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    admin:
      properties:
        bootstrap.servers: kafka-service:29092
    producer:
      bootstrap-servers: kafka-service:29092
    consumer:
      bootstrap-servers: kafka-service:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: consumer-1
      properties:
        spring.json.trusted.packages: "com.jordanec.store.*"
        acks: all
        retries: 3
        retry.backoff.ms: 1000
  sql:
    init:
      platform: mysql
logging:
  level:
    root: INFO
    com:
      jordanec: DEBUG