application:
  name: processor
server:
  port: 8081
  servlet:
    context-path: /store
spring:
  profiles:
    active: local
#logging:
#  level:
#    org:
#      springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    admin:
      properties:
        bootstrap.servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
  cloud.stream:
    function:
      definition: orderProcessor
    bindings:
      orderProcessor-in-0:
        destination: order-events
      orderProcessor-out-0:
        destination: order-notifications
    kafka:
      bindings:
        orderProcessor-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        orderProcessor-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
      binder:
        defaultBrokerPort: 29092
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    #    template:
    #      default-topic: order-events
    consumer:
      #      bootstrap-servers: kafka:9092,kafka:9093,kafka:9094
      bootstrap-servers: kafka-service:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-events_shipment

logging:
  level:
    root: INFO
#    org:
#      springframework: INFO
#    com:
#      jordanec: INFO