application:
  name: shipment
  scheduler:
      shipmentDispatcher:
        enabled: true
        cron: "0 0/5 * 1/1 * ?"
server:
  port: 8081
  servlet:
    context-path: /store
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
#logging:
#  level:
#    org:
#      springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/store_processor
    name: store_processor
    username: store
    password: store
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      #      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    admin:
      properties:
        bootstrap.servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
  cloud.stream:
    function:
      definition: orderProcessor
    bindings:
      orderProcessor-in-0:
        destination: order-events
      orderProcessor-out-0:
        destination: order-notifications
    kafka:
      bindings:
        orderProcessor-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        orderProcessor-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
      binder:
        defaultBrokerPort: 29092
#        brokers:
#          - localhost
  sql:
    init:
      platform: mysql

#  kafka:
##    template:
##      default-topic: order-events
#    consumer:
##      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#      bootstrap-servers: localhost:9092,kafka-service:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: order-events_shipment

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/store_processor
    name: store_consumer
    username: store
    password: store
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      #      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    #    template:
    #      default-topic: order-events
    consumer:
      #      bootstrap-servers: kafka:9092,kafka:9093,kafka:9094
      bootstrap-servers: kafka-service:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-events_shipment
  sql:
    init:
      platform: mysql
logging:
  level:
    root: INFO
#    org:
#      springframework: INFO
#    com:
#      jordanec: INFO