application:
  name: order
  web:
    allowed-origins: 'http://172.17.0.2:31042,http://localhost,http://localhost:4200,http://localhost:3000,http://localhost:80,http://192.168.1.19:4200,http://192.168.1.19:3000,http://192.168.1.19:80'
    allowed-methods: 'GET,OPTIONS,PUT,POST,DELETE'
  scheduler:
    random-order-creator:
      enabled: true
      cron: "0 0/1 * 1/1 * ?"
server:
  port: 8080
  servlet:
    context-path: /store
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/store_producer
    username: store
    name: store_producer
    password: store
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: create
#      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql
  kafka:
    producer:
#      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:29092
logging:
  level:
    root: INFO
    com:
      jordanec: DEBUG
#    org:
#      springframework: DEBUG
